name: Generate workshops from list
on: workflow_dispatch
jobs:
  generatevalues:
    name: Generate values
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin"
      - run: "bash generate_workshops_yaml.sh"
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Adding generated $(echo $(date +'%m-%d-%H-%M-%S'))"
          git push