name: Update Galaxy

on: workflow_dispatch

jobs:
  gxyupdate:
    name: Helm update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: save kubeconfig
        shell: bash
        run: mkdir -p ~/.kube && echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Install Kubectl
        run: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl && kubectl version
      - name: Add gxy helm repo
        run: |
          helm repo add bioc https://github.com/Bioconductor/helm-charts/raw/devel
          helm repo update
      - name: helm upgrade
        run: helm upgrade --install --create-namespace -n gxy-bioc gxy bioc/galaxy --version 4.10.2 --reuse-values -f generated/workshop-toolconf-values.yaml -f generated/workshop-values.yaml
